changes

diff --git a/.github/workflows/flutter-build.yml b/.github/workflows/flutter-build.yml
--- a/.github/workflows/flutter-build.yml
+++ b/.github/workflows/flutter-build.yml
@@ -117,8 +117,9 @@ jobs:
           python3 .\build.py --portable --hwcodec --flutter --vram --skip-portable-pack
           Remove-Item -Path usbmmidd_v2\Win32 -Recurse
           Remove-Item -Path "usbmmidd_v2\deviceinstaller64.exe", "usbmmidd_v2\deviceinstaller.exe", "usbmmidd_v2\usbmmidd.bat"
-          mv ./flutter/build/windows/x64/runner/Release ./rustdesk
-          mv -Force .\usbmmidd_v2 ./rustdesk
+          mkdir ./nikandesk
+          mv ./flutter/build/windows/x64/runner/Release ./nikandesk
+          mv -Force .\usbmmidd_v2 ./nikandesk
 
       - name: find Runner.res
         # Windows: find Runner.res (compiled from ./flutter/windows/runner/Runner.rc), copy to ./Runner.res
@@ -141,21 +142,21 @@ jobs:
         if: ${{ inputs.upload-artifact }}
         with:
           name: topmostwindow-artifacts
-          path: './rustdesk'
+          path: './nikandesk'
 
       - name: Upload unsigned
         if: env.UPLOAD_ARTIFACT == 'true'
         uses: actions/upload-artifact@master
         with:
           name: rustdesk-unsigned-windows-${{ matrix.job.arch }}
-          path: rustdesk
+          path: nikandesk
 
       - name: Sign rustdesk files
         if: env.UPLOAD_ARTIFACT == 'true' && env.SIGN_BASE_URL != ''
         shell: bash
         run: |
           pip3 install requests argparse
-          BASE_URL=${{ secrets.SIGN_BASE_URL }} SECRET_KEY=${{ secrets.SIGN_SECRET_KEY }} python3 res/job.py sign_files ./rustdesk/
+          BASE_URL=${{ secrets.SIGN_BASE_URL }} SECRET_KEY=${{ secrets.SIGN_SECRET_KEY }} python3 res/job.py sign_files ./nikandesk/
 
       - name: Build self-extracted executable
         shell: bash
@@ -163,19 +164,28 @@ jobs:
         run: |
           pushd ./libs/portable
           pip3 install -r requirements.txt
-          python3 ./generate.py -f ../../rustdesk/ -o . -e ../../rustdesk/rustdesk.exe
+          python3 ./generate.py -f ../../nikandesk/ -o . -e ../../nikandesk/nikandesk.exe
           popd
           mkdir -p ./SignOutput
-          mv ./target/release/rustdesk-portable-packer.exe ./SignOutput/nikandesk-${{ env.VERSION }}-${{ matrix.job.arch }}.exe
+          mv ./target/release/nikandesk-portable-packer.exe ./SignOutput/nikandesk-${{ env.VERSION }}-${{ matrix.job.arch }}.exe
 
       - name: Add MSBuild to PATH
         uses: microsoft/setup-msbuild@v2
+
+      - name: List all files in Package/bin directory
+        run: |
+          ls ./Package/bin -R
+
+      - name: List files in Release directory
+        run: |
+          ls ./Package/bin/x64/Release/en-us/
 
       - name: Build msi
         if: env.UPLOAD_ARTIFACT == 'true'
         run: |
           pushd ./res/msi
-          python preprocess.py --arp -d ../../rustdesk
+          mkdir ../../nikandesk
+          python preprocess.py --arp -d ../../nikandesk
           nuget restore msi.sln
           msbuild msi.sln -p:Configuration=Release -p:Platform=x64 /p:TargetVersion=Windows10
           mv ./Package/bin/x64/Release/en-us/Package.msi ../../SignOutput/nikandesk-${{ env.VERSION }}-${{ matrix.job.arch }}.msi
@@ -198,127 +208,127 @@ jobs:
             ./SignOutput/nikandesk-*.exe
 
   # The fallback for the flutter version, we use Sciter for 32bit Windows.
-  build-for-windows-sciter:
-    name: ${{ matrix.job.target }} (${{ matrix.job.os }})
-    runs-on: ${{ matrix.job.os }}
-    # Temporarily disable this action due to additional test is needed.
-    # if: false
-    strategy:
-      fail-fast: false
-      matrix:
-        job:
-          # - { target: i686-pc-windows-msvc        , os: windows-2022                  }
-          # - { target: x86_64-pc-windows-gnu       , os: windows-2022                  }
-          - { target: i686-pc-windows-msvc, os: windows-2022, arch: x86 }
-          # - { target: aarch64-pc-windows-msvc, os: windows-2022 }
-    steps:
-      - name: Export GitHub Actions cache environment variables
-        uses: actions/github-script@v6
-        with:
-          script: |
-            core.exportVariable('ACTIONS_CACHE_URL', process.env.ACTIONS_CACHE_URL || '');
-            core.exportVariable('ACTIONS_RUNTIME_TOKEN', process.env.ACTIONS_RUNTIME_TOKEN || '');
+  # build-for-windows-sciter:
+  #   name: ${{ matrix.job.target }} (${{ matrix.job.os }})
+  #   runs-on: ${{ matrix.job.os }}
+  #   # Temporarily disable this action due to additional test is needed.
+  #   # if: false
+  #   strategy:
+  #     fail-fast: false
+  #     matrix:
+  #       job:
+  #         # - { target: i686-pc-windows-msvc        , os: windows-2022                  }
+  #         # - { target: x86_64-pc-windows-gnu       , os: windows-2022                  }
+  #         - { target: i686-pc-windows-msvc, os: windows-2022, arch: x86 }
+  #         # - { target: aarch64-pc-windows-msvc, os: windows-2022 }
+  #   steps:
+  #     - name: Export GitHub Actions cache environment variables
+  #       uses: actions/github-script@v6
+  #       with:
+  #         script: |
+  #           core.exportVariable('ACTIONS_CACHE_URL', process.env.ACTIONS_CACHE_URL || '');
+  #           core.exportVariable('ACTIONS_RUNTIME_TOKEN', process.env.ACTIONS_RUNTIME_TOKEN || '');
 
-      - name: Checkout source code
-        uses: actions/checkout@v3
+  #     - name: Checkout source code
+  #       uses: actions/checkout@v3
 
-      - name: Install LLVM and Clang
-        uses: rustdesk-org/install-llvm-action-32bit@master
-        with:
-          version: ${{ env.LLVM_VERSION }}
+  #     - name: Install LLVM and Clang
+  #       uses: rustdesk-org/install-llvm-action-32bit@master
+  #       with:
+  #         version: ${{ env.LLVM_VERSION }}
 
-      - name: Install Rust toolchain
-        uses: dtolnay/rust-toolchain@v1
-        with:
-          toolchain: nightly-2023-10-13-${{ matrix.job.target }} # must use nightly here, because of abi_thiscall feature required
-          targets: ${{ matrix.job.target }}
-          components: 'rustfmt'
+  #     - name: Install Rust toolchain
+  #       uses: dtolnay/rust-toolchain@v1
+  #       with:
+  #         toolchain: nightly-2023-10-13-${{ matrix.job.target }} # must use nightly here, because of abi_thiscall feature required
+  #         targets: ${{ matrix.job.target }}
+  #         components: 'rustfmt'
 
-      - uses: Swatinem/rust-cache@v2
-        with:
-          prefix-key: ${{ matrix.job.os }}-sciter
+  #     - uses: Swatinem/rust-cache@v2
+  #       with:
+  #         prefix-key: ${{ matrix.job.os }}-sciter
 
-      - name: Setup vcpkg with Github Actions binary cache
-        uses: lukka/run-vcpkg@v11
-        with:
-          vcpkgDirectory: C:\vcpkg
-          vcpkgGitCommitId: ${{ env.VCPKG_COMMIT_ID }}
+  #     - name: Setup vcpkg with Github Actions binary cache
+  #       uses: lukka/run-vcpkg@v11
+  #       with:
+  #         vcpkgDirectory: C:\vcpkg
+  #         vcpkgGitCommitId: ${{ env.VCPKG_COMMIT_ID }}
 
-      - name: Install vcpkg dependencies
-        run: |
-          $VCPKG_ROOT/vcpkg install --triplet x86-windows-static --x-install-root="$VCPKG_ROOT/installed"
-        shell: bash
+  #     - name: Install vcpkg dependencies
+  #       run: |
+  #         $VCPKG_ROOT/vcpkg install --triplet x86-windows-static --x-install-root="$VCPKG_ROOT/installed"
+  #       shell: bash
 
-      - name: Build rustdesk
-        id: build
-        shell: bash
-        run: |
-          python3 res/inline-sciter.py
-          # Patch sciter x86
-          sed -i 's/branch = "dyn"/branch = "dyn_x86"/g' ./Cargo.toml
-          cargo build --features inline,vram,hwcodec --release --bins
-          mkdir -p ./Release
-          mv ./target/release/rustdesk.exe ./Release/rustdesk.exe
-          curl -LJ -o ./Release/sciter.dll https://github.com/c-smile/sciter-sdk/raw/master/bin.win/x32/sciter.dll
-          echo "output_folder=./Release" >> $GITHUB_OUTPUT
-          curl -LJ -o ./usbmmidd_v2.zip https://github.com/rustdesk-org/rdev/releases/download/usbmmidd_v2/usbmmidd_v2.zip
-          unzip usbmmidd_v2.zip
-          # Do not remove x64 files, because the user may run the 32bit version on a 64bit system.
-          # Do not remove ./usbmmidd_v2/deviceinstaller64.exe, as x86 exe cannot install and uninstall drivers when running on x64,
-          # we need the x64 exe to install and uninstall the driver.
-          rm -rf ./usbmmidd_v2/deviceinstaller.exe ./usbmmidd_v2/usbmmidd.bat
-          mv ./usbmmidd_v2 ./Release || true
+  #     - name: Build rustdesk
+  #       id: build
+  #       shell: bash
+  #       run: |
+  #         python3 res/inline-sciter.py
+  #         # Patch sciter x86
+  #         sed -i 's/branch = "dyn"/branch = "dyn_x86"/g' ./Cargo.toml
+  #         cargo build --features inline,vram,hwcodec --release --bins
+  #         mkdir -p ./Release
+  #         mv ./target/release/rustdesk.exe ./Release/rustdesk.exe
+  #         curl -LJ -o ./Release/sciter.dll https://github.com/c-smile/sciter-sdk/raw/master/bin.win/x32/sciter.dll
+  #         echo "output_folder=./Release" >> $GITHUB_OUTPUT
+  #         curl -LJ -o ./usbmmidd_v2.zip https://github.com/rustdesk-org/rdev/releases/download/usbmmidd_v2/usbmmidd_v2.zip
+  #         unzip usbmmidd_v2.zip
+  #         # Do not remove x64 files, because the user may run the 32bit version on a 64bit system.
+  #         # Do not remove ./usbmmidd_v2/deviceinstaller64.exe, as x86 exe cannot install and uninstall drivers when running on x64,
+  #         # we need the x64 exe to install and uninstall the driver.
+  #         rm -rf ./usbmmidd_v2/deviceinstaller.exe ./usbmmidd_v2/usbmmidd.bat
+  #         mv ./usbmmidd_v2 ./Release || true
 
-      - name: find Runner.res
-        # Windows: find Runner.res (compiled from ./flutter/windows/runner/Runner.rc), copy to ./Runner.res
-        # Runner.rc does not contain actual version, but Runner.res does
-        continue-on-error: true
-        shell: bash
-        run: |
-          runner_res=$(find . -name "Runner.res");
-          if [ "$runner_res" == "" ]; then
-            echo "Runner.res: not found";
-          else
-            echo "Runner.res: $runner_res";
-            cp $runner_res ./libs/portable/Runner.res;
-            echo "list ./libs/portable/Runner.res";
-            ls -l ./libs/portable/Runner.res;
-          fi
+  #     - name: find Runner.res
+  #       # Windows: find Runner.res (compiled from ./flutter/windows/runner/Runner.rc), copy to ./Runner.res
+  #       # Runner.rc does not contain actual version, but Runner.res does
+  #       continue-on-error: true
+  #       shell: bash
+  #       run: |
+  #         runner_res=$(find . -name "Runner.res");
+  #         if [ "$runner_res" == "" ]; then
+  #           echo "Runner.res: not found";
+  #         else
+  #           echo "Runner.res: $runner_res";
+  #           cp $runner_res ./libs/portable/Runner.res;
+  #           echo "list ./libs/portable/Runner.res";
+  #           ls -l ./libs/portable/Runner.res;
+  #         fi
 
-      - name: Sign rustdesk files
-        if: env.UPLOAD_ARTIFACT == 'true' && env.SIGN_BASE_URL != ''
-        shell: bash
-        run: |
-          pip3 install requests argparse
-          BASE_URL=${{ secrets.SIGN_BASE_URL }} SECRET_KEY=${{ secrets.SIGN_SECRET_KEY }} python3 res/job.py sign_files ./Release/
+  #     - name: Sign rustdesk files
+  #       if: env.UPLOAD_ARTIFACT == 'true' && env.SIGN_BASE_URL != ''
+  #       shell: bash
+  #       run: |
+  #         pip3 install requests argparse
+  #         BASE_URL=${{ secrets.SIGN_BASE_URL }} SECRET_KEY=${{ secrets.SIGN_SECRET_KEY }} python3 res/job.py sign_files ./Release/
 
-      - name: Build self-extracted executable
-        shell: bash
-        run: |
-          pushd ./libs/portable
-          pip3 install -r requirements.txt
-          python3 ./generate.py -f ../../Release/ -o . -e ../../Release/rustdesk.exe
-          popd
-          mkdir -p ./SignOutput
-          mv ./target/release/rustdesk-portable-packer.exe ./SignOutput/rustdesk-${{ env.VERSION }}-${{ matrix.job.arch }}-sciter.exe
-          mv ./Release ./rustdesk
-          tar czf rustdesk-${{ env.VERSION }}-${{ matrix.job.arch }}.tar.gz rustdesk
+  #     - name: Build self-extracted executable
+  #       shell: bash
+  #       run: |
+  #         pushd ./libs/portable
+  #         pip3 install -r requirements.txt
+  #         python3 ./generate.py -f ../../Release/ -o . -e ../../Release/rustdesk.exe
+  #         popd
+  #         mkdir -p ./SignOutput
+  #         mv ./target/release/rustdesk-portable-packer.exe ./SignOutput/rustdesk-${{ env.VERSION }}-${{ matrix.job.arch }}-sciter.exe
+  #         mv ./Release ./rustdesk
+  #         tar czf rustdesk-${{ env.VERSION }}-${{ matrix.job.arch }}.tar.gz rustdesk
 
-      - name: Sign rustdesk self-extracted file
-        if: env.UPLOAD_ARTIFACT == 'true' && env.SIGN_BASE_URL != ''
-        shell: bash
-        run: |
-          BASE_URL=${{ secrets.SIGN_BASE_URL }} SECRET_KEY=${{ secrets.SIGN_SECRET_KEY }} python3 res/job.py sign_files ./SignOutput/
+  #     - name: Sign rustdesk self-extracted file
+  #       if: env.UPLOAD_ARTIFACT == 'true' && env.SIGN_BASE_URL != ''
+  #       shell: bash
+  #       run: |
+  #         BASE_URL=${{ secrets.SIGN_BASE_URL }} SECRET_KEY=${{ secrets.SIGN_SECRET_KEY }} python3 res/job.py sign_files ./SignOutput/
 
-      - name: Publish Release
-        uses: softprops/action-gh-release@v1
-        if: env.UPLOAD_ARTIFACT == 'true'
-        with:
-          prerelease: true
-          tag_name: ${{ env.TAG_NAME }}
-          files: |
-            ./SignOutput/rustdesk-*.exe
-            ./rustdesk-*.tar.gz
+  #     - name: Publish Release
+  #       uses: softprops/action-gh-release@v1
+  #       if: env.UPLOAD_ARTIFACT == 'true'
+  #       with:
+  #         prerelease: true
+  #         tag_name: ${{ env.TAG_NAME }}
+  #         files: |
+  #           ./SignOutput/rustdesk-*.exe
+  #           ./rustdesk-*.tar.gz
 
   # build-for-macOS-arm64-selfhost:
   #   # use build-for-macOS instead
